from Myro import *
setVoice("en-sc+f1")
speak("I_: am Shin_jini, the_Knock-Knock jokes robot")
speak("Knock_: Knock")
setVoice("zh-yue")
speak("Who's _: there")
setVoice("en-sc+f1")
speak("Robin")
setVoice("zh-yue")
speak("Robin_: who?")
setVoice("en-sc+f1")
speak("Robin u.") 
speak("Hand over your cash.")